Repository realkarych/seqwall, pull requests merged in 2025-05, with the labels that each got.

#12 Add tests (e2e) infra (#5)
  .ci/Dockerfile
  .ci/run_tests.sh
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  Makefile
  test_data/README.md
  test_data/valid/base/001.sql
  test_data/valid/base/002.sql
  test_data/valid/base/003.sql
  test_data/valid/base/004.sql
  test_data/valid/base/005.sql
  test_data/valid/base/006.sql
  test_data/valid/base/007.sql
  test_data/wrong/003_fail/001.sql
  test_data/wrong/003_fail/002.sql
  test_data/wrong/003_fail/003.sql
  test_data/wrong/003_fail/004.sql
  test_data/wrong/003_fail/005.sql
  test_data/wrong/003_fail/006.sql
  test_data/wrong/003_fail/007.sql
  test_data/wrong/006_fail/001.sql
  test_data/wrong/006_fail/002.sql
  test_data/wrong/006_fail/003.sql
  test_data/wrong/006_fail/004.sql
  test_data/wrong/006_fail/005.sql
  test_data/wrong/006_fail/006.sql
  test_data/wrong/006_fail/007.sql
  test_data/wrong/007_fail/001.sql
  test_data/wrong/007_fail/002.sql
  test_data/wrong/007_fail/003.sql
  test_data/wrong/007_fail/004.sql
  test_data/wrong/007_fail/005.sql
  test_data/wrong/007_fail/006.sql
  test_data/wrong/007_fail/007.sql
Labels: infra

#13 Add golangci-lint
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  main.go
  pkg/driver/postgres.go
  pkg/seqwall/errors.go
  pkg/seqwall/migrations.go
  pkg/seqwall/staircase.go
Labels: infra

#16 [Bug] scan function row: sql: Scan error on column index 1, name "routine_type": converting NULL to string is unsupported (#15)
  .ci/run_tests.sh
  pkg/driver/postgres.go
  pkg/seqwall/staircase.go
  test_data/valid/base/008.sql
  test_data/wrong/007_fail/007.sql
Labels: bug

#17 Update READMEs, add md-linter
  .github/workflows/ci.yml
  README.md
  pkg/README.md
  test_data/README.md
  test_data/valid/001/001.sql
  test_data/valid/001/002.sql
  test_data/valid/001/003.sql
  test_data/valid/001/004.sql
  test_data/valid/001/005.sql
  test_data/valid/001/006.sql
  test_data/valid/001/007.sql
  test_data/valid/001/008.sql
Labels: documentation, infra

#18 Refactor srcs
  pkg/driver/README.md
  pkg/driver/entities.go
  pkg/driver/postgres.go
  pkg/seqwall/README.md
  pkg/seqwall/differs.go
  pkg/seqwall/entities.go
  pkg/seqwall/placeholders.go
  pkg/seqwall/staircase.go
Labels: infra

#20 Migrate to golangci-lint v2 (#14)
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  main.go
  pkg/driver/postgres.go
  pkg/seqwall/differs.go
  pkg/seqwall/entities.go
  pkg/seqwall/staircase.go
Labels: infra

#23 Add unit tests
  main_test.go
  pkg/seqwall/differs.go
  pkg/seqwall/differs_test.go
  pkg/seqwall/entities_test.go
  pkg/seqwall/migrations_test.go
Labels: invalid, infra

#22 fix: export Version variable to enable --version via ldflags
  .github/workflows/publish.yml
  Makefile
  main.go
Labels: enhancement

#25 Add staircase_test.go; fix .gitignore
  .gitignore
  pkg/seqwall/staircase.go
  pkg/seqwall/staircase_unix_test.go
  pkg/seqwall/staircase_windows_test.go
Labels: infra

#27 Add README badges
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  README.md
Labels: infra

#32 Introduce docker images
  .github/workflows/publish.yml
  .markdownlint.json
  Dockerfile
  README.md
Labels: help wanted, infra

#33 Fix Dockerfile
  .github/workflows/publish.yml
  Dockerfile
  README.md
Labels: infra

#35 Upgrade step 3: redundant up-down-up to re-actualize
  README.md
  pkg/seqwall/staircase.go
Labels: enhancement
